title: Ngoc-Truong Nguyen
markdown: kramdown
url: "https://ntruongn.github.io"
baseurl: ""

author:
  name: Ngoc-Truong Nguyen
  email: 2k1.nguyenngoctruong@gmail.com
  twitter: daulpavid
  mastodon_instance: infosec.exchange
  mastodon_handle: daulpavid
  github: ntruongn
  linkedin: daulpavid
description:
  Bullshit goes here.
tagline:
  Hack the planet!

darkhack:
  date_format: "%x"
  font_awesome: "357d91f838"

theme: darkhack

collections:
  disclosures:
    output: true
  researchs:
    output: true
  yet_another_collection:
    output: true
